apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: teslamate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: teslamate/grafana:2.2.0
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_USER
              value: teslamate
            - name: DATABASE_NAME
              value: teslamate
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: GF_SERVER_ROOT_URL
              value: https://teslamate.example.com/grafana
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_AUTH_PROXY_ENABLED
              value: "true"
            - name: GF_AUTH_PROXY_HEADER_NAME
              value: X-Forwarded-Email
            - name: GF_AUTH_PROXY_HEADER_PROPERTY
              value: email
            - name: GF_AUTH_PROXY_AUTO_SIGN_UP
              value: "true"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_AUTH_DISABLE_SIGNOUT_MENU
              value: "true"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_USERS_AUTO_ASSIGN_ORG_ROLE
              value: Admin
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: teslamate-db-secret
                  key: POSTGRES_PASSWORD
          securityContext:
            runAsUser: 472
            runAsGroup: 0
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 500m
